---
# tasks file for ers-db
- name: Installing MySQL-python
  yum: name=MySQL-python state=installed
- name: Populating my.cnf
  template:
   src: my-cnf
   dest: /etc/my.cnf
- name: Starting and Enabling mysql
  service: name=mysql state=started enabled=yes
- name: Remove empty users
  mysql_user:
   login_user: root
   login_password: ""
   check_implicit_admin: yes
   user: ""
   host: "{{ item }}"
   state: absent
  with_items:
  - localhost
  - ""
  - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  - localhost.localdomain
  - "::1"
  - 127.0.0.1
- name: Change root password of mysql
  mysql_user:
   login_user: root
   login_password: "{{ DB_PASS }}"
   check_implicit_admin: yes
   user: root
   password: "{{ DB_PASS }}"
   host: "{{ item }}"
   priv: "*.*:ALL,GRANT"
  with_items:
  - localhost
  - "%"
  - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
- name: Remove test DB
  mysql_db:
   name: test
   login_user: root
   login_password: "{{ DB_PASS }}"
   state: absent
- name: Creating refill user
  mysql_user:
   login_user: root
   login_password: "{{ DB_PASS }}"
   check_implicit_admin: yes
   user: refill
   password: "{{ DB_PASS }}"
   host: "{{ item }}"
   priv: "*.*:ALL,GRANT"
  with_items:
  - localhost
  - "%"
  - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
- name: Creating replicate user
  mysql_user:
   login_user: root
   login_password: "{{ DB_PASS }}"
   check_implicit_admin: yes
   user: replicate
   password: "{{ DB_PASS }}"
   host: "{{ item }}"
   priv: "*.*:REPLICATION SLAVE"
  with_items:
  - localhost
  - "%"
  - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
- name: Creating report user
  mysql_user:
   login_user: root
   login_password: "{{ DB_PASS }}"
   check_implicit_admin: yes
   user: report
   password: "{{ DB_PASS }}"
   host: "{{ item }}"
   priv: "*.*:SELECT,GRANT"
  with_items:
  - localhost
  - "%"
  - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
