---
- hosts: controller1
  vars:
   ADMIN_PASS: 56dda5cced74f3168ba6
   VIP: 10.10.10.4
  environment:
   OS_USERNAME: admin
   OS_PASSWORD: "{{ ADMIN_PASS }}"
   OS_PROJECT_NAME: admin
   OS_USER_DOMAIN_NAME: Default
   OS_PROJECT_DOMAIN_NAME: Default
   OS_AUTH_URL: http://{{ VIP }}:35357/v3
   OS_IDENTITY_API_VERSION: 3
  roles:
  - server_provision
