#Reference: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html
Configutation:
  name: Default

  Properties:
    Property:
      name: log-path
      value: "/var/seamless/log/credit-services"

  Appenders:
    #Appender will write the logs to console
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%highlight{[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n}{FATAL=red blink, ERROR=red, WARN=yellow bold, INFO=blue, DEBUG=green bold, TRACE=black}"
    #Appender will write the logs to File
    File:
      name: File_Appender
      fileName: ${log-path}/credit-services.log
      PatternLayout:
        pattern: "%highlight{[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n}{FATAL=red blink, ERROR=red, WARN=yellow bold, INFO=blue, DEBUG=green bold, TRACE=black}"
    #Appender will write the logs to rolling file
    RollingFile:
      - name: Rolling_Appender
        fileName: ${log-path}/credit-services-rolling.log
        filePattern: "${log-path}/credit-services.log.%d{yyyy-MM-dd-hh-mm}.gz"
        PatternLayout:
          pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
        Policies:
        #Roll the log file and zip if if the size exceeds 1MB
          SizeBasedTriggeringPolicy:
            size: 1 MB
        #Keep below defined number of rolling files before deleting them
        DefaultRollOverStrategy:
          max: 45

  Loggers:
      #Root logging level for application
      Root:
        level: info
        AppenderRef:
          - ref: Console_Appender
          - ref: File_Appender
      #Application specific logging
      Logger:
        - name: com.seamless.credit
          additivity: false
          level: debug
          AppenderRef:
            - ref: Console_Appender
              level: info
            - ref: File_Appender
            - ref: Rolling_Appender